name: CI/CD Pipeline

on:
  push: # Trigger on push events
    branches:
      - "*" # All branches
  pull_request: # Trigger on pull request events
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use .env file
        run: echo "${{ secrets.ENV_API }}" > .env

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Delete .env file
        run: rm .env
        id: delete-env-file # Assign an ID to this step

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use .env file
        run: echo "${{ secrets.ENV_BUILD }}" > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tienlong1106/git_cicd_api:latest
