name: CI/CD Pipeline

on:
    push:
        tag:
            - "*"

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest

        services:
            mongodb:
                image: mongo:latest
                ports:
                    - 27017:27017

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.11.1"

            - name: Clear npm cache
              run: npm cache clean --force

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/') # Only run on the main branch
        outputs:
            tag_name: ${{ steps.extract_tag.outputs.tag_name }}
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

            - name: Extract tag name
              id: extract_tag
              run: echo "tag_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: |
                      tienlong1106/git_cicd_api:${{ steps.extract_tag.outputs.tag_name }}

    update_config_repo:
        name: Update Config Repo with New Image Version
        runs-on: ubuntu-latest
        needs: push_to_registry # Ensure this job runs after push_to_registry

        steps:
            - name: Checkout config repo
              uses: actions/checkout@v2
              with:
                  repository: nguyentienlong1106/VDT_Config_api
                  ref: "main"
                  token: ${{ secrets.G }}

            - name: Update image tag in values.yaml
              run: |
                  sed -i 's/^  *tag:.*/  tag: ${{ needs.push_to_registry.outputs.tag_name }}/g' values.yaml

            - name: Commit and push changes
              run: |
                  git config --global user.name "nguyentienlong1106"
                  git config --global user.email "tienlong1106@gmail.com"
                  git add values.yaml
                  git commit -m "Update image tag to ${{ needs.push_to_registry.outputs.tag_name }}"
                  git push
